name: sync-beta
run-name: Keep the beta branch syncronised with the master branch and active PRs
on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize, labeled]
  
  push:
    branches:
      - 'master'

jobs:
    merge-master:
        name: Merge pr or master branches into beta
        runs-on: ubuntu-latest
        if: |
          github.ref_name == 'master' || 
          (github.event.pull_request.draft == false &&
          github.event.pull_request.mergeable == true &&
          github.event.pull_request.head.repo.fork == false &&
          contains(github.event.pull_request.labels.*.name, 'beta'))

        steps:
            - name: merge with beta
              uses: devmasx/merge-branch@master
              with:
                type: now
                target_branch: beta
                github_token: ${{ secrets.GITHUB_TOKEN }}